### ISSUE TITLE
example use-cases of hbsfy

### ISSUE THREAD

**Issue by ducin** [epeli/node-hbsfy#40]
Hi, forgive me if you find this issue untypical, but I simply don't get the idea of where I would need to use hbsfy? I've been using handlebars in SPA projects, I know how do they work. And I do understand the main concept of browserify. But I can't think of any real world example I might use hbsfy in. I read all readme docs and I didn't found it there asa well. Please give me a hint on that.

**Comment by epeli** [comment]
If you don't need hbsfy then great! Maybe it has served it's purpose.

But Handlebars and Browserify do (did?!) expose an incompatible API between the two and hbsfy is just an API clue which makes them work together. With hbsfy you can use Handlebars inside of Browserify instead of manually using them separately.

**Comment by pushred** [comment]
I find it to be the most convenient, and efficient, way of precompiling templates. By requiring them close to wherever I'm rendering them, the dependencies are totally explicit in the node way. I'm requiring templates just like I require modules and JSON files. I'm also compiling just the templates I need clientside, and no more. Precompiling of course makes for faster template functions.

**Comment by elgubenis** [comment]
:+1:  @pushred

**Comment by kirbysayshi** [comment]
I'm going to close this issue for now. Please reopen if there are still unanswered questions!
